### ISSUE TITLE
Streaming over internet

### ISSUE THREAD

**Issue by danielsore** [sepehr-laal/livecam#3]
I'm trying to use LIvecam to stream over the internet, I can see my video using router ip plus port while in network, but when I try to see the video using 4G or other network I can't see it. It has some problem to stream using TCP over internet?

**Comment by 3p3r** [comment]
There are lots of things that can go wrong when you stream over Internet, NAT is the first which comes to my mind in your case. You need to have publicly visible addresses and ports server side. It's been a long time since I looked at this but:

```
'ui_addr' : '127.0.0.1', <-- must be public
'ui_port' : 11000,

'broadcast_addr' : '127.0.0.1', <-- must be public
'broadcast_port' : 12000,

'gst_tcp_addr' : '127.0.0.1', <-- can be private
'gst_tcp_port' : 10000,
```

Out of these, `ui_XX` and `broadcast_XX` must be publicly visible over Internet. `gst_tcp_XX` can be local to your broadcast server (only node.js process needs to listen to it).

With those two public, it *should* work in theory.
